import './data.js';
import { isSupabaseConfigured, supabase } from './supabase.js';
import { loadWaterData, markAlertResolved } from './supabase-data.js';

let D = window.JalData;
let dataState = { status: 'idle', error: '' };
const protectedRoutes = ['dashboard', 'devices', 'monitoring', 'alerts', 'reports', 'about'];
const nav = [['home', 'Home', 'H'], ['dashboard', 'Dashboard', 'D'], ['devices', 'Devices', 'S'], ['monitoring', 'Monitoring', 'M'], ['alerts', 'Alerts', 'A'], ['reports', 'Reports', 'R'], ['about', 'About', 'i']];
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]);
let sessionUser = null;
const currentUser = () => sessionUser;
const initials = (name = '') => name.split(' ').filter(Boolean).slice(0, 2).map(word => word[0]).join('').toUpperCase() || 'JN';
const activeAlerts = () => D.alerts.filter(alert => String(alert.status).toLowerCase() === 'active').length;
const badge = value => `<span class="badge ${String(value).toLowerCase().replaceAll(' ', '-')}">${esc(value)}</span>`;
const metric = (icon, label, value, note, tone = 'teal') => `<article class="metric-card ${tone}"><div class="metric-icon">${icon}</div><div><p>${label}</p><h3>${value}</h3><small>${note}</small></div></article>`;
const head = (eyebrow, title, text, action = '') => `<section class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lede">${text}</p></div>${action}</section>`;
const demoNotice = compact => `<div class="demo-notice ${compact ? 'compact' : ''}"><b>${dataState.status === 'error' ? 'Connection issue' : dataState.status === 'loading' ? 'Loading data' : 'Live data'}</b><span>${compact ? D.mode : (dataState.error || D.sourceNote)}</span></div>`;
function chart(labels, points, color = '#0b8b8c') { if (points.length < 2) return `<p class="muted empty-state">No reading history is available yet.</p>`; const w = 680, h = 220, p = 22, max = Math.max(...points) * 1.12, min = Math.min(...points) * .85; const range = max - min || 1; const xy = points.map((v, i) => `${p + i * ((w - p * 2) / (points.length - 1))},${h - p - ((v - min) / range) * (h - p * 2)}`); return `<div class="chart-wrap"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Water trend chart"><defs><linearGradient id="chart-gradient" x1="0" x2="0" y1="0" y2="1"><stop stop-color="${color}" stop-opacity=".25"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><g class="grid"><line x1="22" y1="30" x2="658" y2="30"/><line x1="22" y1="95" x2="658" y2="95"/><line x1="22" y1="160" x2="658" y2="160"/></g><polygon points="${p},${h-p} ${xy.join(' ')} ${w-p},${h-p}" fill="url(#chart-gradient)"/><polyline points="${xy.join(' ')}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${xy.map(point => { const [x, y] = point.split(','); return `<circle cx="${x}" cy="${y}" r="4" fill="#fff" stroke="${color}" stroke-width="3"/>`; }).join('')}</svg><div class="chart-labels">${labels.map(label => `<span>${label}</span>`).join('')}</div></div>`; }
function readings(rows = D.readings) { return `<div class="table-wrap"><table><thead><tr><th>Date and time</th><th>Availability</th><th>Flow rate</th><th>Usage</th><th>Status</th></tr></thead><tbody>${rows.length ? rows.map(r => `<tr><td>${esc(r.time)}</td><td><b>${r.availability}%</b></td><td>${r.flow} L/min</td><td>${r.usage}%</td><td>${badge(r.status)}</td></tr>`).join('') : '<tr><td colspan="5" class="empty-state">No readings are available for your account.</td></tr>'}</tbody></table></div>`; }
function shell(content, active) { const user = currentUser(), name = esc(userName(user)); const accountControl = user ? `<div class="user-menu"><button class="avatar" title="${name}">${initials(userName(user))}</button><div><b>${name}</b><button class="logout-button" onclick="logout()">Log out</button></div></div>` : '<a class="login-link" href="#login">Log in</a>'; return `<aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">~</span><span>Jal<span>Nigrani</span><small>SMART WATER SYSTEM</small></span></a><nav>${nav.map(([id, label, icon]) => `<a href="#${id}" class="${active === id ? 'active' : ''}"><i>${icon}</i>${label}${id === 'alerts' ? `<em>${activeAlerts()}</em>` : ''}</a>`).join('')}</nav><div class="side-bottom"><div class="demo-dot"></div><span>Demo mode</span></div></aside><div class="scrim" onclick="toggleMenu()"></div><main><header class="topbar"><button class="menu-btn" onclick="toggleMenu()">Menu</button><div class="breadcrumb">JalNigrani <span>/</span> ${active[0].toUpperCase() + active.slice(1)}</div><div class="top-actions">${demoNotice(true)}${accountControl}</div></header>${content}<footer>2026 JalNigrani - Frontend demonstration only</footer></main>`; }
function auth(mode = 'login') { const reg = mode === 'register'; const unavailable = !isSupabaseConfigured; return `<main class="auth-page"><section class="auth-panel"><a class="brand auth-brand" href="#login"><span class="brand-mark">~</span><span>Jal<span>Nigrani</span><small>SMART WATER SYSTEM</small></span></a><div class="auth-copy"><p class="eyebrow">SUPABASE AUTHENTICATION</p><h1>${reg ? 'Create your account.' : 'Welcome back.'}</h1><p>${reg ? 'Register to access the JalNigrani workspace.' : 'Sign in with your Supabase account.'}</p></div>${unavailable ? '<p class="form-message error config-message">Supabase is not configured. Add VITE_SUPABASE_PUBLISHABLE_KEY to .env.local, then restart Vite.</p>' : ''}<form class="auth-form" id="auth-form" novalidate>${reg ? '<label>Full name<input name="name" type="text" autocomplete="name" placeholder="Gungun Jaiswal" required></label>' : ''}<label>Email<input name="email" type="email" autocomplete="email" placeholder="you@example.com" required></label><label>Password<input name="password" type="password" autocomplete="${reg ? 'new-password' : 'current-password'}" placeholder="At least 6 characters" required></label>${reg ? '<label>Confirm password<input name="confirmPassword" type="password" autocomplete="new-password" placeholder="Re-enter your password" required></label>' : ''}<p id="form-message" class="form-message" role="status"></p><button class="btn primary auth-submit" type="submit" ${unavailable ? 'disabled' : ''}>${reg ? 'Create account' : 'Log in'}</button></form><p class="auth-switch">${reg ? 'Already registered?' : 'New to JalNigrani?'} <a href="#${reg ? 'login' : 'register'}">${reg ? 'Log in' : 'Create an account'}</a></p><p class="auth-note">Authentication is securely handled by Supabase. Your password is never stored by this frontend.</p></section><aside class="auth-aside"><div>${demoNotice()}<p class="eyebrow light">SMART WATER MANAGEMENT</p><h2>See usage patterns before they become problems.</h2><p>Explore a polished monitoring experience with clearly marked simulated data.</p></div></aside></main>`; }
function home() { return shell(`<div class="home"><section class="hero"><div class="hero-copy">${demoNotice()}<p class="eyebrow light">SMART WATER MANAGEMENT</p><h1>Every drop, <em>clearly understood.</em></h1><p>JalNigrani brings availability, consumption, flow, and operational alerts into one focused workspace.</p><div class="hero-actions"><a class="btn primary" href="#dashboard">Explore dashboard -></a><a class="btn ghost" href="#about">How it works</a></div><div class="trust"><span>o</span> Simulated monitoring <span>o</span> Demo alerts <span>o</span> Better planning</div></div><div class="hero-visual"><div class="orb one"></div><div class="orb two"></div><div class="water-card"><div class="water-icon">~</div><small>SIMULATED AVAILABILITY</small><b>${D.system.availability}<span>%</span></b><div class="water-bar"><i></i></div><p>Demo operating level <strong>+3.2%</strong></p></div><div class="float-card"><span>-></span><div><small>Simulated flow</small><b>${D.system.flowRate} L/min</b></div></div></div></section><section class="intro section"><p class="eyebrow">WHY JALNIGRANI</p><h2>Water systems deserve better visibility.</h2><p class="section-copy">Unseen consumption and late warnings make managing a limited resource difficult. JalNigrani brings essential monitoring signals into one focused workspace.</p><div class="feature-grid"><article><span>01</span><h3>The problem</h3><p>Fragmented readings can make changing availability and unexpected use hard to identify in time.</p></article><article><span>02</span><h3>The solution</h3><p>A single view of simulated availability, flow, consumption patterns, and operational alerts.</p></article><article><span>03</span><h3>The outcome</h3><p>More confident daily decisions and a clear history to support future planning.</p></article></div></section><section class="feature-band"><div><p class="eyebrow light">BUILT FOR CLARITY</p><h2>From readings to smarter action.</h2></div><div class="mini-features"><p><b>Usage monitoring</b><span>See simulated daily consumption and flow at a glance.</span></p><p><b>Overuse alerts</b><span>Know when demo patterns need attention.</span></p><p><b>Meaningful history</b><span>Understand sample trends over time.</span></p></div></section><section class="cta"><div><p class="eyebrow">READY TO EXPLORE</p><h2>A clearer picture of your water system starts here.</h2></div><a class="btn primary" href="#dashboard">Open dashboard -></a></section></div>`, 'home'); }
function dashboard() { const s = D.system, user = currentUser(), onlinePercent = D.devices.length ? Math.round((D.devices.filter(device => /online/i.test(device.status)).length / D.devices.length) * 100) : 0; return shell(`${head('OVERVIEW', `Good morning, ${esc(userName(user))}.`, 'Your current water-system data.', '<button class="btn outline" onclick="refreshData()">Refresh data</button>')}<section class="page-data-note">${demoNotice()}</section><section class="metrics">${metric('~', 'Water availability', `${s.availability}%`, 'Latest recorded level')}${metric('->', 'Current flow', `${s.flowRate} L/min`, 'Latest recorded reading', 'blue')}${metric('U', 'Daily consumption', `${s.dailyUsage.toLocaleString()} L`, 'From recorded usage', 'violet')}${metric('!', 'Active alerts', activeAlerts(), 'Alerts requiring review', 'orange')}</section><section class="content-grid"><article class="panel large"><div class="panel-head"><div><h2>Water availability</h2><p>Recent reservoir readings</p></div></div>${chart(D.trends.labels, D.trends.availability)}<div class="chart-stat"><span>Current level <b>${s.availability}%</b></span><span>Target range <b>75-90%</b></span></div></article><article class="panel status-panel"><div class="panel-head"><div><h2>Device status</h2><p>Connected monitoring devices</p></div>${badge(s.status)}</div><div class="system-visual"><div class="ring"><b>${onlinePercent}<small>%</small></b><span>devices online</span></div></div><div class="status-list">${D.devices.length ? D.devices.slice(0, 3).map(device => `<p><span>o</span> ${esc(device.name)} <b>${esc(device.status)}</b></p>`).join('') : '<p class="muted empty-state">No devices are assigned to your account.</p>'}</div></article></section><section class="split-grid"><article class="panel"><div class="panel-head"><div><h2>Recent readings</h2><p>Latest monitoring data</p></div><a href="#monitoring">View all -></a></div>${readings(D.readings.slice(0, 3))}</article><article class="panel activity"><div class="panel-head"><div><h2>Recent activity</h2><p>Latest alert activity</p></div></div>${D.activity.length ? D.activity.map(a => `<div class="activity-row"><i>${a.icon}</i><div><b>${a.title}</b><p>${a.text}</p></div><time>${a.time}</time></div>`).join('') : '<p class="muted empty-state">No alert activity yet.</p>'}</article></section>`, 'dashboard'); }
function devices() { return shell(`${head('DEVICES', 'Monitoring devices', 'ESP32 devices will appear here after they are registered. No hardware connection is assumed.', '<button class="btn outline" onclick="refreshData()">Refresh data</button>')}<section class="page-data-note">${demoNotice()}</section><article class="panel full-panel"><div class="panel-head"><div><h2>Registered devices</h2><p>Devices assigned to your account</p></div></div>${D.devices.length ? `<div class="table-wrap"><table><thead><tr><th>Name</th><th>Zone</th><th>Status</th></tr></thead><tbody>${D.devices.map(device => `<tr><td><b>${esc(device.name)}</b></td><td>${esc(device.zone)}</td><td>${badge(device.status)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="muted empty-state">No device connected. Register an ESP32 device after the hardware setup is complete.</p>'}</article>`, 'devices'); }
function monitoring() { const s = D.system; return shell(`${head('SIMULATED MONITORING', 'Water monitoring', 'Explore sample availability, flow, and consumption trends. No live hardware is connected.', '<button class="btn outline" onclick="showToast(\'Showing the latest simulated reading set.\')">Refresh demo</button>')}<section class="page-data-note">${demoNotice()}</section><div class="filterbar" data-filterbar><button class="selected">Today</button><button>24 hours</button><button>7 days</button><span></span><button>All zones</button><button>Select date</button></div><section class="metrics">${metric('~', 'Current availability', `${s.availability}%`, 'Simulated operating level')}${metric('->', 'Flow rate', `${s.flowRate} L/min`, 'Simulated current reading', 'blue')}${metric('U', 'Usage today', `${s.dailyUsage.toLocaleString()} L`, 'Simulated daily consumption', 'violet')}</section><section class="content-grid"><article class="panel large"><div class="panel-head"><div><h2>Flow and usage trend</h2><p>Simulated litres per minute - today</p></div><div class="legend"><i></i> Sample flow rate</div></div>${chart(D.trends.labels, D.trends.flow, '#3878c9')}</article><article class="panel availability-card"><div class="panel-head"><div><h2>Availability</h2><p>Simulated reservoir capacity</p></div></div><div class="level"><div class="level-fill"><span>${s.availability}%</span></div></div><div class="level-info"><span>0%<b>Demo target: 75-90%</b>100%</span></div><p class="muted">Estimated simulated availability</p><h2>${s.estimatedAvailable.toLocaleString()} L</h2></article></section><article class="panel full-panel"><div class="panel-head"><div><h2>Historical simulated readings</h2><p>Detailed sample readings from today</p></div><button class="link-button" onclick="showToast(\'Download is a frontend placeholder in Demo Mode.\')">Download CSV</button></div>${readings()}</article>`, 'monitoring'); }
function alerts() { const resolved = D.alerts.filter(a => a.status === 'Resolved').length; return shell(`${head('ALERT CENTRE', 'Stay ahead of usage changes.', 'Review simulated system notifications and overuse warnings.', '<button class="btn outline" onclick="showToast(\'Alert settings are a frontend placeholder.\')">Alert settings</button>')}<section class="page-data-note">${demoNotice()}</section><section class="metrics alert-metrics">${metric('!', 'Active alerts', activeAlerts(), 'Simulated alerts to review', 'orange')}${metric('!', 'High priority', D.alerts.filter(a => a.priority === 'High' && a.status === 'Active').length, 'Simulated overuse detection', 'red')}${metric('+', 'Resolved this week', resolved, 'Sample resolved alerts', 'teal')}</section><div class="filterbar" data-filterbar><button class="selected">All alerts</button><button>Active</button><button>Warnings</button><button>Resolved</button><span></span><button>Priority</button><button>Date range</button></div><section class="alert-list">${D.alerts.map((a, i) => `<article class="alert-card ${a.status === 'Resolved' ? 'resolved' : ''}"><div class="alert-symbol ${a.priority.toLowerCase()}">${a.status === 'Resolved' ? '+' : '!'}</div><div class="alert-content"><div><h3>${a.type}</h3>${badge(a.priority)}</div><p>${a.detail}</p><small>${a.time} - ${a.status} simulated alert</small></div><div class="alert-actions">${badge(a.status)}${a.status === 'Active' ? `<button class="link-button" onclick="resolveAlert(${i})">Mark resolved</button>` : ''}</div></article>`).join('')}</section>`, 'alerts'); }
function reports() { return shell(`${head('REPORTS AND HISTORY', 'Understand sample water patterns.', 'Explore simulated statistics and historical demo trends for planning.', '<button class="btn primary" onclick="showToast(\'Report export is a frontend placeholder in Demo Mode.\')">Export report</button>')}<section class="page-data-note">${demoNotice()}</section><div class="filterbar" data-filterbar><button class="selected">This month</button><button>This week</button><button>Last 90 days</button><span></span><button>01 Sep - 17 Sep</button></div><section class="metrics">${metric('U', 'Total water used', D.reports[2].water, 'Simulated monthly usage', 'violet')}${metric('->', 'Average flow', D.reports[2].flow, 'Simulated monthly average', 'blue')}${metric('~', 'Average availability', D.reports[2].availability, 'Within demo target range', 'teal')}${metric('!', 'Alert events', D.alerts.length, 'Sample records in this demo', 'orange')}</section><section class="content-grid"><article class="panel large"><div class="panel-head"><div><h2>Availability trend</h2><p>Simulated daily average for the past week</p></div><div class="legend"><i></i> Sample availability</div></div>${chart(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], D.trends.weeklyAvailability)}</article><article class="panel"><div class="panel-head"><div><h2>Usage summary</h2><p>Sample distribution by period</p></div></div><div class="summary-bars">${D.reports.map((r, i) => `<div><span>${r.period}</span><b>${r.water}</b><i><em style="width:${[42, 74, 92][i]}%"></em></i></div>`).join('')}</div></article></section><article class="panel full-panel"><div class="panel-head"><div><h2>Period comparison</h2><p>Simulated historic usage and averages</p></div></div><div class="table-wrap"><table><thead><tr><th>Period</th><th>Total water used</th><th>Average flow</th><th>Availability</th><th>Change</th></tr></thead><tbody>${D.reports.map(r => `<tr><td><b>${r.period}</b></td><td>${r.water}</td><td>${r.flow}</td><td>${r.availability}</td><td><span class="up">${r.change}</span></td></tr>`).join('')}</tbody></table></div></article>`, 'reports'); }
function about() { return shell(`${head('ABOUT JALNIGRANI', 'Water management, made visible.', 'A smart monitoring interface for understanding and planning around water resources.')}<section class="about-hero"><div><p class="eyebrow">OUR PURPOSE</p><h2>Make every water decision more informed.</h2><p>JalNigrani translates operational signals into a simple, useful view. This frontend demonstration is built around availability, flow, usage, and timely alerts.</p></div><div class="about-stat"><b>Demo</b><span>simulated data and frontend-only authentication</span></div></section><section class="feature-grid about-grid"><article><span>01</span><h3>The challenge</h3><p>Without a clear view of supply and consumption, unusual patterns can go unnoticed and planning becomes reactive.</p></article><article><span>02</span><h3>Our approach</h3><p>Organise monitoring data into trends and surface the signals that support a timely decision.</p></article><article><span>03</span><h3>How it works</h3><p>Future monitoring points can feed availability and flow readings into indicators, alerts, and history.</p></article></section><section class="benefits"><p class="eyebrow">DESIGNED TO HELP</p><h2>Useful across the places water matters most.</h2><div><p><b>Communities</b><span>Build confidence through clear visibility of shared water resources.</span></p><p><b>Institutions</b><span>Support day-to-day operations with practical usage insights.</span></p><p><b>Facilities</b><span>Identify patterns and make better use of every available litre.</span></p></div></section><section class="future"><span>*</span><div><p class="eyebrow">FUTURE SCOPE</p><h2>A foundation ready to grow.</h2><p>The UI keeps demo data and rendering separate, so real hardware or service integrations can be introduced later without rebuilding the frontend.</p></div></section>`, 'about'); }
function bindAuth(mode) {
  const form = document.getElementById('auth-form');
  form?.addEventListener('submit', async event => {
    event.preventDefault();
    const message = document.getElementById('form-message');
    const submitButton = form.querySelector('button[type="submit"]');
    const values = Object.fromEntries(new FormData(form));
    const email = String(values.email || '').trim().toLowerCase();
    const password = String(values.password || '');
    const say = (text, type) => { message.textContent = text; message.className = `form-message ${type}`; };
    const setSubmitting = submitting => {
      submitButton.disabled = submitting;
      submitButton.textContent = submitting ? (mode === 'register' ? 'Creating account...' : 'Logging in...') : (mode === 'register' ? 'Create account' : 'Log in');
    };
    if (!isSupabaseConfigured || !supabase) return say('Supabase is not configured. Add your publishable key to .env.local.', 'error');
    if (!/^\S+@\S+\.\S+$/.test(email)) return say('Enter a valid email address.', 'error');
    if (mode === 'register') {
      const name = String(values.name || '').trim().replace(/\s+/g, ' ');
      if (name.length < 2) return say('Enter your full name.', 'error');
      if (password.length < 6) return say('Password must be at least 6 characters.', 'error');
      if (password !== values.confirmPassword) return say('Passwords do not match.', 'error');
      setSubmitting(true); say('Creating your Supabase account...', '');
      try {
        const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } });
        if (error) return say(error.message, 'error');
        if (!data.user) return say('Supabase did not return a user. Please try again.', 'error');
        if (data.user.identities?.length === 0) return say('An account with this email already exists. Please log in instead.', 'error');
        if (!data.session) return say('Account created successfully. Check your email to confirm your account, then log in.', 'success');
        sessionUser = data.user;
        showToast('Account created successfully.'); location.hash = 'dashboard';
      } catch (error) {
        say(error?.message || 'Unable to reach Supabase. Check your internet connection and try again.', 'error');
      } finally {
        setSubmitting(false);
      }
      return;
    }
    setSubmitting(true); say('Signing in with Supabase...', '');
    try {
      const { data, error } = await supabase.auth.signInWithPassword({ email, password });
      if (error) return say(error.message, 'error');
      if (!data.user || !data.session) return say('Supabase could not create a session. Please try again.', 'error');
      sessionUser = data.user;
      showToast(`Welcome, ${userName(data.user)}.`); location.hash = 'dashboard';
    } catch (error) {
      say(error?.message || 'Unable to reach Supabase. Check your internet connection and try again.', 'error');
    } finally {
      setSubmitting(false);
    }
  });
}
async function resolveAlert(index) { const alert = D.alerts[index]; if (!alert || String(alert.status).toLowerCase() !== 'active') return; try { await markAlertResolved(alert); await refreshData(); showToast('Alert marked resolved.'); } catch (error) { showToast(error.message || 'Unable to update the alert.'); } }
function toggleMenu() { document.body.classList.toggle('nav-open'); }
async function logout() { if (supabase) await supabase.auth.signOut(); sessionUser = null; document.body.classList.remove('nav-open'); location.hash = 'login'; }
function showToast(message) { const toast = document.createElement('div'); toast.className = 'toast'; toast.textContent = message; document.body.append(toast); setTimeout(() => toast.remove(), 2800); }
function bindFilterBars() { document.querySelectorAll('[data-filterbar]').forEach(bar => bar.addEventListener('click', event => { if (event.target.tagName !== 'BUTTON') return; bar.querySelectorAll('button').forEach(button => button.classList.remove('selected')); event.target.classList.add('selected'); showToast(`${event.target.textContent} filter selected (demo).`); })); }
function userName(user) { return D.profile?.full_name || user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'User'; }
function hardwareEmpty(active) { const isMonitoring = active === 'monitoring'; const title = isMonitoring ? 'Water monitoring' : 'Your dashboard'; return shell(`${head(isMonitoring ? 'MONITORING' : 'OVERVIEW', title, 'No device is connected and no sensor readings are available yet.', '<button class="btn outline" onclick="refreshData()">Refresh data</button>')}<section class="page-data-note">${demoNotice()}</section><article class="panel full-panel"><div class="panel-head"><div><h2>No device connected</h2><p>Your ESP32 integration has not been configured yet.</p></div></div><p class="muted empty-state">Connect and register an ESP32 device later to start receiving water readings. This screen does not display generated or test readings as live hardware data.</p><a class="btn outline" href="#devices">View devices</a></article>`, active); }
function render() {
  const route = (location.hash.slice(1) || 'home').toLowerCase();
  if (['login', 'register'].includes(route)) { if (currentUser()) { location.hash = 'dashboard'; return; } document.getElementById('app').innerHTML = auth(route); bindAuth(route); return; }
  if (protectedRoutes.includes(route) && !currentUser()) { location.hash = 'login'; return; }
  const views = { home, dashboard, devices, monitoring, alerts, reports, about };
  const noHardwareData = ['dashboard', 'monitoring'].includes(route) && !D.readings.length;
  document.getElementById('app').innerHTML = noHardwareData ? hardwareEmpty(route) : (views[route] || home)(); bindFilterBars(); document.body.classList.remove('nav-open'); window.scrollTo(0, 0);
}
async function initializeApp() {
  localStorage.removeItem('jalnigrani_users');
  localStorage.removeItem('jalnigrani_current_user');
  if (supabase) {
    const { data } = await supabase.auth.getSession();
    sessionUser = data.session?.user || null;
    if (sessionUser) await refreshData(false);
    supabase.auth.onAuthStateChange(async (_event, session) => { sessionUser = session?.user || null; if (sessionUser) await refreshData(); else { D = window.JalData; dataState = { status: 'idle', error: '' }; render(); } });
  }
  render();
}
async function refreshData(shouldRender = true) {
  dataState = { status: 'loading', error: '' };
  if (shouldRender) render();
  try { D = await loadWaterData(); dataState = { status: 'ready', error: '' }; }
  catch (error) { D = { ...window.JalData, mode: 'Unavailable', sourceNote: 'Unable to load live data' }; dataState = { status: 'error', error: error?.message || 'Unable to reach Supabase.' }; }
  if (shouldRender) render();
}
window.toggleMenu = toggleMenu; window.logout = logout; window.showToast = showToast; window.resolveAlert = resolveAlert; window.refreshData = refreshData;
window.addEventListener('hashchange', render); initializeApp();
